serializers:
  json:
    host: json
    port: 5001
  pickle:
    host: pickle
    port: 5002
  yaml:
    host: yaml
    port: 5003
  xml:
    host: xml
    port: 5004

proxy:
  host: proxy
  port: 5000