serializers:
  json:
    host: json
  pickle:
    host: pickle
  yaml:
    host: yaml
  xml:
    host: xml
  proto:
    host: proto
  avro:
    host: avro
  msgpack:
    host: msgpack

proxy:
  host: proxy